package com.connection.http

enum class TiposComandos {
    StartCam,
    StopCam,
    InitSDK,
    StopSDK,
    StartDroneCam,
    StopDroneCam,
    ChangeVisionMode,
    ConfigureMission,
    PrepareMission,
    StartMission,
    PauseMission,
    ResumeMission,
    CancelMission,
    GimballYawAdd,
    GimballYawDrop,
    GimballPitchAdd,
    GimballPitchDrop,
    GimballRollAdd,
    GimballRollDrop,
    GimbalReset,
    Stop,
    GoUp,
    GoDown,
    TurnLeft,
    TurnRight,
    GoFront,
    GoBack,
    GoLeft,
    GoRight,
    TakeOff,
    Land,
    SetAsHomePoint,
    GoHome,
    CancelReturn
}